### ISSUE TITLE
erorr in cityscapes 

### ISSUE THREAD

**Issue by bj5546** [LikeLy-Journey/SegmenTron#10]
in  cityscapes datasets，a error happened . assert: DataLoader worker process 0 in line 57 assert (value in self._mapping). I changed it in line 51 to self._mapping = np.array(range(0, len(self._key))).astype('int32'). It works! Is it right?

**Comment by LielinJiang** [comment]
you use your custom data? if you use cityscape, you do not need to change anything.

**Comment by LikeLy-Journey** [comment]
> in cityscapes datasets，a error happened . assert: DataLoader worker process 0 in line 57 assert (value in self._mapping). I changed it in line 51 to self._mapping = np.array(range(0, len(self._key))).astype('int32'). It works! Is it right?

you use your custom data? if you use cityscape, you do not need to change anything.
