### ISSUE TITLE
mobilenetv3+LR-ASPP ?

### ISSUE THREAD

**Issue by pawopawo** [LikeLy-Journey/SegmenTron#16]
Thanks for your excellent work!

Will you reproduce mobilenetv3+LR-ASPP ?

**Comment by LikeLy-Journey** [comment]
what is the mean of LR?
i consider to add more backbones, but not recently.

**Comment by pawopawo** [comment]
![image](https://user-images.githubusercontent.com/38682321/74259137-5e0f8380-4d32-11ea-837e-c84fb86b2dc8.png)
