### ISSUE TITLE
espnetv2 and enet head

### ISSUE THREAD

**Issue by WaterKnight1998** [LikeLy-Journey/SegmenTron#24]
Hi,

In espnetv2 and enet models I am troubling to find the classifier head for adjusting it to my DataSet.

Thank you very much for the implementation of all the models.

**Comment by LikeLy-Journey** [comment]
enet head: https://github.com/LikeLy-Journey/SegmenTron/blob/master/segmentron/models/enet.py#L54   https://github.com/LikeLy-Journey/SegmenTron/blob/master/segmentron/models/enet.py#L105 
espnetv2 head: https://github.com/LikeLy-Journey/SegmenTron/blob/master/segmentron/models/espnetv2.py#L31-L33  https://github.com/LikeLy-Journey/SegmenTron/blob/master/segmentron/models/espnetv2.py#L51-L52
num class of your dataset: https://github.com/LikeLy-Journey/SegmenTron/blob/master/segmentron/models/segbase.py#L21

actually, i only collect many models from others repo.

**Comment by WaterKnight1998** [comment]
Thank you very much. Can i use your code for my personal project? 

I think that I will need to refactor a bit of your code, so maybe I'll fork it.

**Comment by LielinJiang** [comment]
of course, you can do anything with it. it is my pleasure if this repo can help you.

**Comment by LikeLy-Journey** [comment]
Of course, you can do anything with it. It is my pleasure that this repo can help you.
