### ISSUE TITLE
about demo.py

### ISSUE THREAD

**Issue by y-kl8** [LikeLy-Journey/SegmenTron#27]
somebody know how to use the demo.py?

what is the command?

**Comment by LielinJiang** [comment]
`python tools/demo.py --config-file your_config_file --input-img your-img-path-or-your-img-dir` will be ok.

**Comment by LikeLy-Journey** [comment]
`python tools/demo.py --config-file your-config-file --input-img your-img-path-or-your-img-dir`
will be ok

**Comment by andeyeluguo** [comment]
@LikeLy-Journey I found it did not work use your demo. the outputed picture will be fulled with yellow pixels.

**Comment by WesleyYue** [comment]
@andeyeluguo If you are getting a single class for the entire image you're probably running inference on random weights; make sure you actually loaded a model. The output should print something like load test model from https://github.com/LikeLy-Journey/SegmenTron/blob/e6218e6/segmentron/models/model_zoo.py#L34

You need to download weights from the readme and modify the TEST_MODEL_PATH in the config files if you're using the repo out of the box.
