### ISSUE TITLE
Calculation method about mIoU

### ISSUE THREAD

**Issue by jianlong-yuan** [LikeLy-Journey/SegmenTron#29]
pixAcc = 1.0 * self.total_correct / (2.220446049250313e-16 + self.total_label)  # remove np.spacing(1)
        IoU = 1.0 * self.total_inter / (2.220446049250313e-16 + self.total_union)
        # mIoU = IoU.mean().item()
        mIoU = 1.0 * self.total_inter.sum().float() / (2.220446049250313e-16 + self.total_union.sum().float())

I think it's a common calculation method in various leaderboard.

**Comment by LikeLy-Journey** [comment]
sorry, i didn't get you
