### ISSUE TITLE
How to test the FPS?

### ISSUE THREAD

**Issue by y-kl8** [LikeLy-Journey/SegmenTron#40]
![image](https://user-images.githubusercontent.com/37499637/79059853-7ad42300-7cb1-11ea-942e-0af25592e92a.png)

my test code like this,.  The speed of deeplabv3-pluse-mobilenetv2(use ASPP and Decoder) is faster than the deeplabv3-pluse-mobilenetv2(doesn't use ASPP and Decoder). Do somebody know why?

**Comment by LikeLy-Journey** [comment]
You can reference this: https://github.com/juntang-zhuang/ShelfNet/blob/citys_lw/ShelfNet18_realtime/test_speed.py. Your test script contain the time of copying output tensor from gpu to cpu, which may take much more time than model inference because the size of output tensor is large.
