### ISSUE TITLE
about demo.py

### ISSUE THREAD

**Issue by xiaozhen18239228065** [LikeLy-Journey/SegmenTron#45]
python demo.py --config-file configs/pascal_voc_deeplabv3_plus.yaml --input_img '2012_004317.jpg'

![image](https://user-images.githubusercontent.com/37620610/80817228-a3da3a80-8c03-11ea-99bc-3729c490cd4c.png)

**Comment by xiaozhen18239228065** [comment]
Please tell me why this happens

**Comment by LikeLy-Journey** [comment]
you should make sure you load the trained model correctly. you can reference this issue #27
