### ISSUE TITLE
about inference time(FPS)?

### ISSUE THREAD

**Issue by xiaoyufenfei** [LikeLy-Journey/SegmenTron#5]
How do you test the speed of different segmentation models, sometimes, I am a little confused about the speed of some papers description？

**Comment by LikeLy-Journey** [comment]
I am confused too. i just run model 100 times, batch size is 1, then average them.

**Comment by sumaliqinghua** [comment]
I am confused tooo.

**Comment by xiaoyufenfei** [comment]
Despite the doubts, but some project released the fps test script, such as [ShelfNet](https://github.com/juntang-zhuang/ShelfNet), [CGNet](https://github.com/wutianyiRosun/CGNet) for our research...

**Comment by xiaoyufenfei** [comment]
And most of the articles report an average of 100 frames for the frames per second (FPS) measurement, this test method may be mostly deployed...
